### ISSUE TITLE
I had problems with touchscreen

### ISSUE THREAD

**Issue by plucker** [TxBillbr/octodash-hyperpixel-fix#2]
Brand new pi with 5.4 kernel and new hyperpixel 4 and all worked following your great instructions but the x-axis on the touchscreen was inverted.  I had to modify config.txt to read :

`dtoverlay=hyperpixel4:rotate,touchscreen-swapped-x-y,touchscreen-inverted-x`

this was with the power socket at the bottom of the display.  With it at the top you need `touchscreen-inverted-y`

**Comment by TxBillbr** [comment]
Thanks for the update. I am sure other readers will appreciate that.
